kind: pipeline
name: build

steps:
  - name: npm install
    image: node:12-buster-slim
    commands:
      - npm install -g cnpm --registry=https://registry.npm.taobao.org
      - cnpm install
      - cnpm i @nuxtjs/axios
      - cnpm i @nuxtjs/toast
      - cnpm i @nuxtjs/proxy

  - name: npm build
    image: node:12-buster-slim
    commands:
      - npm run build

  - name: docker
    image: plugins/docker
    settings:
      username: yasinshaw
      password:
        from_secret: docker_password
      repo: registry.cn-hangzhou.aliyuncs.com/yasinshaw/yasin_portal
      registry: registry.cn-hangzhou.aliyuncs.com
      mirror: https://mzayqkhl.mirror.aliyuncs.com
      tags: latest

---
kind: pipeline
type: ssh
name: deploy

server:
  host: yasinshaw.com
  user: root
  ssh_key:
    from_secret: ssh_key

steps:
  - name: pull image
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login --username=yasinshaw --password=$DOCKER_PASSWORD registry.cn-hangzhou.aliyuncs.com
      - docker pull registry.cn-hangzhou.aliyuncs.com/yasinshaw/yasin_portal:latest

  - name: remove old container
    failure: ignore
    commands:
      - docker rm -f -v yasin_portal

  - name: start container
    commands:
      - docker run -d --name=yasin_portal --restart=always -p 3001:3000 registry.cn-hangzhou.aliyuncs.com/yasinshaw/yasin_portal:latest
depends_on:
  - build